// Prices and descriptions transcribed from Carta-ZonaFresca.pdf (provided by owner).
// Availability, flavor stock, scoop mappings and allowed extras remain DEMO fixtures.
const fruit = "mango, papaya, banano, durazno y fresa";
const rows = [
  [
    "ensalada-zf",
    "Ensalada Zona Fresca",
    "Ensaladas",
    25000,
    `Helado, ${fruit}, crema de leche, queso, cereal, salsa y chantillí.`,
    2,
    "frutas",
    true,
  ],
  [
    "queso-ensalada",
    "Queso ensalada",
    "Ensaladas",
    23000,
    `Helado, ${fruit}, mucho queso, crema de leche, salsa, chantillí y barquillo.`,
    1,
    "frutas",
  ],
  [
    "ensalada-tradicional",
    "Ensalada tradicional",
    "Ensaladas",
    21000,
    `Helado, ${fruit}, queso, crema de leche, salsa y chantillí.`,
    1,
    "frutas",
  ],
  ["solo-fruta", "Ensalada solo fruta", "Ensaladas", 16000, fruit, 0, "frutas"],
  [
    "copa-zf",
    "Copa Zona Fresca",
    "Copas",
    24000,
    "Cuatro bolas de helado, fresa, brownie, queso, lechera, chantillí, barquillo y cereza.",
    4,
    "conos",
    true,
  ],
  [
    "copa-queso",
    "Copa queso",
    "Copas",
    14000,
    "Helado, lechera, mucho queso, barquillo y chantillí.",
    2,
    "conos",
  ],
  [
    "copa-suiza",
    "Copa suiza",
    "Copas",
    13000,
    "Helado, almendras en hojuelas, chantillí y chocolate caliente.",
    1,
    "conos",
  ],
  [
    "copa-chocolate",
    "Copa chocolate",
    "Copas",
    14000,
    "Helado, chocolate en trocitos, salsa de chocolate, barquillo y chantillí.",
    2,
    "conos",
  ],
  [
    "copa-fresas",
    "Copa fresas con crema",
    "Copas",
    14000,
    "Helado, barquillo, lechera, crema y muchas fresas.",
    1,
    "frutas",
  ],
  [
    "copa-duraznos",
    "Copa duraznos",
    "Copas",
    15000,
    "Helado, lechera, barquillo, crema y muchos duraznos.",
    1,
    "frutas",
  ],
  [
    "salpicon-zf",
    "Salpicón Zona Fresca",
    "Salpicones",
    17000,
    "Helado, salpicón, queso, barquillo, lechera y chantillí.",
    2,
    "salpicon",
    true,
  ],
  [
    "salpicon-tradicional",
    "Salpicón tradicional",
    "Salpicones",
    15000,
    "Helado, salpicón, queso, barquillo, lechera y chantillí.",
    1,
    "salpicon",
  ],
  [
    "salpicon-sencillo",
    "Salpicón sencillo",
    "Salpicones",
    11000,
    "Helado, salpicón, barquillo, lechera y chantillí.",
    1,
    "salpicon",
  ],
  [
    "fondue",
    "Fondue para compartir",
    "Antojos",
    28000,
    "Helado, fresas, chocolate derretido, salsa, chantillí, banano y masmelos.",
    1,
    "waffle",
    true,
  ],
  [
    "banana-split",
    "Banana split",
    "Antojos",
    19000,
    "Helado, banano, queso, barquillo, crema de leche, salsa y chantillí.",
    3,
    "banana",
    true,
  ],
  [
    "brownie",
    "Brownie",
    "Antojos",
    17000,
    "Helado, brownie, fresas, salsa y chantillí.",
    2,
    "waffle",
  ],
  [
    "waffle",
    "Waffle",
    "Antojos",
    18000,
    "Helado, waffle, fresas, banano, nutella, salsa y chantillí.",
    1,
    "waffle",
  ],
  [
    "galleta",
    "Galleta con helado",
    "Antojos",
    13000,
    "Helado, galleta horneada, salsa y chantillí.",
    1,
    "waffle",
  ],
  [
    "oblea",
    "Oblea",
    "Antojos",
    9000,
    "Crema de leche, salsa que prefieras, chantillí y queso.",
    0,
    "waffle",
  ],
  [
    "malteada-zf",
    "Malteada Zona Fresca",
    "Bebidas",
    15000,
    "Una bola de tu helado favorito con chantillí, chips de chocolate y salsa.",
    1,
    "conos",
    true,
  ],
  [
    "malteada-sencilla",
    "Malteada sencilla",
    "Bebidas",
    13000,
    "Una bola del sabor de helado que elijas y salsa.",
    1,
    "conos",
  ],
  [
    "cafe",
    "Café con helado",
    "Bebidas",
    10000,
    "Café con una bola de helado de vainilla, salsa de chocolate y chantillí.",
    1,
    "conos",
  ],
  [
    "batido",
    "Batido saludable",
    "Bebidas",
    14000,
    "Una bola de helado de vainilla light, fresas y granola.",
    1,
    "frutas",
  ],
  [
    "jugos",
    "Jugos naturales",
    "Bebidas",
    10000,
    "Escoge el sabor de tu jugo natural.",
    0,
    "frutas",
  ],
  [
    "limonadas",
    "Limonadas",
    "Bebidas",
    10000,
    "Una pausa refrescante, a tu gusto.",
    0,
    "frutas",
  ],
  ["milo", "Milo", "Bebidas", 10000, "Milo.", 0, "conos"],
  [
    "gaseosa",
    "Gaseosas",
    "Bebidas",
    4000,
    "Presentación y marcas por confirmar.",
    0,
    "frutas",
  ],
  [
    "gusanito",
    "Gusanito",
    "Infantil",
    12000,
    "Helado, gomitas y chantillí.",
    2,
    "infantil",
    true,
  ],
  ["gomita", "Gomita", "Infantil", 10000, "Helado con gomitas.", 1, "infantil"],
  [
    "arepa-zf",
    "Arepa Zona Fresca",
    "Salados",
    25000,
    "Arepa rellena de carne, pollo, chicharrón, hogao, queso, guacamole, maduros y champiñones.",
    0,
    "arepa",
    true,
  ],
  [
    "arepa-tradicional",
    "Arepa tradicional",
    "Salados",
    19000,
    "Arepa rellena de carne, pollo, chicharrón, hogao, queso y guacamole.",
    0,
    "arepa",
  ],
  [
    "perrito",
    "Perrito",
    "Salados",
    6000,
    "Acompañado de tomate, cebolla, ripio de papa y guacamole.",
    0,
    "arepa",
  ],
  [
    "chuzo",
    "Chuzo",
    "Salados",
    19000,
    "Acompañado de arepa con queso mozzarella y guacamole.",
    0,
    "arepa",
  ],
  [
    "concha-sencilla",
    "Concha sencilla",
    "Conos y más",
    5000,
    "Composición por confirmar con el local.",
    0,
    "conos",
  ],
  [
    "concha-especial",
    "Concha especial",
    "Conos y más",
    9000,
    "Composición por confirmar con el local.",
    0,
    "conos",
  ],
  [
    "cucurucho-especial",
    "Cucurucho especial",
    "Conos y más",
    9000,
    "Composición por confirmar con el local.",
    0,
    "conos",
  ],
  [
    "cucurucho-sencillo",
    "Cucurucho sencillo",
    "Conos y más",
    5000,
    "Composición por confirmar con el local.",
    0,
    "conos",
  ],
  [
    "litro",
    "Litro de helado",
    "Conos y más",
    null,
    "Un litro, un solo sabor. Precio pendiente de confirmar.",
    0,
    "conos",
  ],
];
export const flavors = [
  "Vainilla",
  "Chocolate",
  "Fresa",
  "Ron con pasas",
  "Vainilla light",
];
export const additions = [
  { id: "queso", name: "Queso", price: 6000 },
  { id: "fruta", name: "Fruta", price: 4000 },
  { id: "porcion-fruta", name: "Porción de fruta", price: 6000 },
  { id: "cereal", name: "Cereal", price: 4000 },
  { id: "proteina", name: "Proteína en arepas", price: 4000 },
];
export const products = rows.map(
  ([
    id,
    name,
    category,
    price,
    description,
    scoops,
    image,
    featured = false,
  ]) => ({
    id,
    name,
    category,
    price,
    description,
    ingredients: description,
    image: `/images/${image}.jpg`,
    imageNote: "Imagen de referencia de nuestra carta",
    featured,
    available: price !== null && id !== "gaseosa",
    includedScoops: scoops,
    maxScoops: scoops ? scoops + 3 : 0,
    // Additional scoop price is intentionally identified as a fixture, not official pricing.
    extraScoopPrice: 4000,
    flavors:
      id === "cafe"
        ? ["Vainilla"]
        : id === "batido"
          ? ["Vainilla light"]
          : scoops || id === "litro"
            ? flavors
            : [],
    maxFlavors: id === "litro" ? 1 : scoops + 3,
    additions:
      category === "Salados"
        ? id.startsWith("arepa")
          ? ["proteina"]
          : []
        : ["Ensaladas", "Copas", "Salpicones", "Antojos"].includes(category)
          ? ["queso", "fruta", "porcion-fruta", "cereal"]
          : [],
    removals: [
      "banano",
      "queso",
      "helado",
      "chantillí",
      "salsa",
      "cebolla",
      "guacamole",
    ].filter((x) => description.toLowerCase().includes(x)),
    variants:
      id === "jugos"
        ? [
            "Mango",
            "Fresa",
            "Mora",
            "Maracuyá",
            "Banano",
            "Lulo",
            "Mandarina",
            "Guanábana",
          ]
        : id === "limonadas"
          ? ["Cereza", "Mango", "Fresa", "Natural", "Durazno"]
          : [],
    aliases:
      id === "banana-split"
        ? ["banana", "bananas"]
        : id.startsWith("arepa")
          ? ["arepa"]
          : [],
    source: "Carta-ZonaFresca.pdf",
    demo: true,
  }),
);
export const catalogAdapter = {
  get: () => ({
    products,
    flavors,
    additions,
    demo: true,
    notice:
      "Precios de la carta suministrada. Disponibilidad, sabores y reglas de personalización en demostración; pendientes de confirmar.",
  }),
};
